### ISSUE TITLE
cannot read property 'getCharacteristic' of undefined

### ISSUE THREAD

**Issue by akac** [mrjackyliang/homebridge-adt-pulse#23]
### Describe the bug:
I am getting this error when launching - this used to work, but I did a homebridge update and now it crashes.

### Steps to reproduce the bug:
1. Updated to latest versions of plugin and homebridge

### Expected behavior:
Launch ;)

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
```

### Logs related to this bug:

```sh
[3/30/2020, 3:45:36 PM] [ADT-Pulse] Configuring cached accessory... Glass Basement Family (sensor-70)
[3/30/2020, 3:45:36 PM] TypeError: Cannot read property 'getCharacteristic' of undefined
    at ADTPulsePlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-adt-pulse/index.js:165:9)
    at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:386:24)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[3/30/2020, 3:45:36 PM] Got SIGTERM, shutting down Homebridge
```

**Comment by mrjackyliang** [comment]
Please refer to issue #17. It has already been fixed.

**Comment by akac** [comment]
The fix for me was to simply remove the cached accessories file.

**Comment by mrjackyliang** [comment]
Or you can do that, but that also erases the accessories for the other plugins also.
