### ISSUE TITLE
Update not initiating properly

### ISSUE THREAD

**Issue by Danimal1024** [mrjackyliang/homebridge-adt-pulse#67]
When trying to update the plugin, I get this message after the command...

---------------------------
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-adt-pulse@latest

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

Command failed. Please review log for details.
--------------------------------------------------

Does the command look correct? I don't normally pay attention to the command that initiates the update but it seems different than the way it looked when I used to have to update with command line vs. using the HomeBridge platform. Let me know if I missed something or if there is something else needed to update the plugin. I'm running HomeBridge v1.3.5 with Node.js v16.13.0 and NPM v8.1.0

Thanks

**Comment by salsarodriguez** [comment]
Same thing happened to me. This helped me resolve it:
https://github.com/homebridge/homebridge/issues/3002

1. Downgrade node to 14.18.1
sudo hb-service update-node 14.18.1

2. Update npm to the latest version 8
sudo npm i -g npm

3. Update node to 16.13.0
sudo hb-service update-node 16.13.0

4. Re-update npm to the latest version 8
sudo npm i -g npm

**Comment by Danimal1024** [comment]
Those steps worked. Thanks!

**Comment by mrjackyliang** [comment]
Oh that is odd. Mine just warned me and I just accepted the risk of it crashing or something.
